{% set name = "f2c" %}
{% set version = "20210323183018" %}
{% set sha256 = "ca404070e9ce0a9aaa6a71fc7d5489d014ade952c5d6de7efb88de8e24f2e8e0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: libf2c.zip
  url: https://web.archive.org/web/20180419233829/http://www.netlib.org/{{ name }}/src.tgz
  url: https://web.archive.org/web/20210323183018/https://netlib.sandia.gov/f2c/libf2c.zip
  sha256: {{ sha256 }}

build:
  number: 1002
  skip: True  # [vc<14 and win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - unzip  # [not win]
  run:

test:
  commands:
    - test -f ${PREFIX}/include/f2c/f2c.h  # [not win]
    - f2c --version
    - f2c test_main.f && ${CC} test_main.c -L${PREFIX}/lib -lf2c -I${PREFIX}/include -o test_main && ./test_main  # [not win]
  requires:
    - {{ compiler('c') }}
  files:
    - test_main.f

about:
  home: http://www.netlib.org/f2c/
  license: OTHER
  license_family: OTHER
  license_file: permission
  summary: 'f2c is a program to convert Fortran 77 to C code, developed at Bell Laboratories.'
  description:  The standalone f2c program was based on the core of the first complete Fortran 77
                compiler to be implemented, the "f77" program by Feldman and Weinberger.
  doc_url: http://www.netlib.org/f2c/README
  dev_url: http://www.netlib.org/f2c/

extra:
  recipe-maintainers:
    - giacomov
    - jasercion
    - Areustle
