appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: KOHaIuNK6HB2bv9OkYJF9uwaUpxpBhAOjI4koqHZwiIXSzH0Y2uNcnagxcZYkC9+665yAhLlu/lQuPnoT5EnOJLSDOornvBIylMt/PXOln/VJBaed6d3dqWWrP4j8DHM/jeYOf55oHLsH1FlVT8wl62tU4Phtb9FLxTpARgw7LZvIsXPAaOpSSjh50j/GUkR7dHFFDZsoXO9iZdV5mEMuMKornLooxFyHeZCbHnKbCQCjXxv0iZTsbt/noVcXt7M3jbTZU0aj32yLdgxFyhfZ+5yk1MgdWrkk847998Rvj1yX1ZQlEBECoFjs1Y4OPKing8W3nbzGH7VcYSiTlXtp8W283qNOP7sKzOthOIMDNeTtMQbmGQEtTpQvJiO1buaKCWkfwQB3JxLl0lT85lAcHIlGvQj4pSXbzL5Hr+WocIThf73QC3HBbIOd2WPgFhQZuSN0+7f20VWaF10TV24b42n7311gnv2FWfp2js2mOsoi+gsPPMxEj8hqeccUUJ/WtDDw1vIAfdD1ihgRkQusF24tZLkg7uVLHMIzmF5hyFrXcZwo++5YyAzYJZQnktiz9DrD+uV9EmRPBuqkzawsTOiSrvVeNmKnbAx4hOvQ4468Aw74WP8Cdi8NdwdHVs147xdZKcqYM7riw7SeHzSq84ddaPWDpTRt8IIdYEGy9I=}
conda_forge_output_validation: true
