travis:
  secure:
    BINSTAR_TOKEN: S1rO7E8ocUtndX2nxR/Vf9wCFcwX0OxUMC108ym2bdrdCCtwPz+XXc7/Gaim21kS4DqHdWnEhsWKWtXeaxGzfOL1KqbkQwvE1fx8oWhunlwqIrHGR8fuVajDbsHQkyCDRakLlK3rRMFEj/4wpdNyTPt/ID+Gc0rM1SlptbowTbnss5hMvs0z1WrMYGpGEj9umO2iJaJZkqaahD2rzue7iWsbsQwCTOTwZJwZWSOZ2A2Yzry1M607Q4BX/PSfcqEDVcl6EJewABxChbN6mxZP8bnHCR8tcd+QcE0HfnOtN0ciFg0+br2IUMr8nHYD7q3cv6dITYZZmITmjNw+9RzXokgVuvw9xEun4tlfPV/MRVmyTRXdK8MguevqsnXJgaZaVMvLuJkZSL2xLccmzjS6YNbTESyF6R/y+W0zvKN5zFVqhEThbcNzGzB1tGo44Uj0Ohf+G0wdwjy9aWE1gWt5H9B/mSmC7mEZayRL8yitOttkd/BzHHl6MfmqCL0TLjwf5VzA+KVg+gQ3tj6PfXlUOzH4yLR1jSkdiw+fA6La4SDloDEH1oNFnk2rnrTCBPiw7qotnrHDOmGzhCqB1VWMH6CzdJdd/fS7LrDBkCBmVBSZjj2K+RPh3T+cVV/wm6lI57aT32caMu4XTqmBIiuRiaTzwOCD9fzKEZ+3xftQsb0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
